name: {{cookiecutter.project_name}}
channels:
 - conda-forge
dependencies:
 - jupyter=1.0.0
 - python=3.7.3
 - pandas=0.24.2
 - numpy=1.16.4
 - scipy=1.3.0
 - matplotlib=3.1.0
 - seaborn=0.9.0
 - plotly=3.10.0
 - pyodbc=4.0.26
 
 - pip:
    - bumpversion==0.5.3
    - python-dotenv==0.10.3
